<?xml version="1.0" encoding="UTF-8"?>
<!-- Created with WSDLGenerator 1.0.0 by Amadeus SAS -->
<!-- "Amadeus Proprietary and Confidential Information: unauthorized use and disclosure strictly forbidden. 2010 - Amadeus s.a.s - All Rights Reserved." -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://wsdl.amadeus.com/HotelContent_v1_v2" xmlns:int="http://wsdl.amadeus.com/HotelContent_v1" xmlns:awsse="http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd" name="AVRABE_HotelContent_1.0_2.0" targetNamespace="http://wsdl.amadeus.com/HotelContent_v1_v2">
  <wsdl:documentation>Versions: [interface: 1.0 ; technical: 2.0]</wsdl:documentation>
  <wsdl:import namespace="http://wsdl.amadeus.com/HotelContent_v1" location="HotelContent_1.0.wsdl" />
  <wsdl:types>
    <xs:schema>
      <xs:import schemaLocation="WBS_Session-2.0.xsd" namespace="http://xml.amadeus.com/ws/2009/01/WBS_Session-2.0.xsd" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="Session_2.0">
    <wsdl:part element="awsse:Session" name="session" />
  </wsdl:message>
  <wsdl:binding type="int:HotelContent_PT" name="HotelContent_Binding">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Hotel_ContentNotifReport">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWABEAVR/Hotel_ContentNotifReport_1.0" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header part="session" message="tns:Session_2.0" use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header part="session" message="tns:Session_2.0" use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Hotel_DescriptiveInfo">
      <soap:operation soapAction="http://webservices.amadeus.com/1ASIWABEAVR/OTA_HotelDescriptiveInfoRQ_07.1_1A2007A" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header part="session" message="tns:Session_2.0" use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header part="session" message="tns:Session_2.0" use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HotelContent_Service">
    <wsdl:port binding="tns:HotelContent_Binding" name="HotelContent_Port">
      <soap:address location="https://nodeD1.test.webservices.amadeus.com" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>


<!-- Build Key: 1F8B080000000000000025CDC10A82401485E1BD4F7197452833929BD98D6626144446AE07BBC925BD23E324F4F64DB5FDE0FCA74246673C59064F23CEDE8C938254C82C96692C25EC1DDDCD3B88CAA4DA4AA84ED78D104A88A86D7647A8FE7BEB604137878C0299884444C540C860A669A0EED757A01732FEE520B7F649DC43C93D31C24AE7E53AD4F419D88C1802BAA9DB80FA76896AF6E81EA60B7CB01E87C20660FF3DF9005FCFB1B1BB000000 -->